services:
- docker
script:
- bash create_images.sh
deploy:
  provider: gcs
  edge: true
  bucket: hdvent-monitoring
  cleanup: false
  acl: public-read
  local_dir: ./deploy/
  upload_dir: $TRAVIS_BRANCH
  on:
    all_branches: true
  secret_access_key:
    secure: fmvBRH7gnI9cmAidxEo3CT4S5e73+zzOn//7t/5+KZoBxQrCpGkmr+hpPjrgJ4zUZqhKRVcpNziLwviiPYThaM8B+1VO+H9s3SmaVn4538VWyTFFTBdV7/6has6d7akkwCpaqMJ1RzNmPGb8sBCGM5QON1EUrbfXmsJQbEMYIVWC+Q8tzjT13UdkdNJY/8sQYEWsnPiRxmO0ps4cPBQXeBTccjPzyMw4eneQNfLDSJ+8HntiVV0UWdd61ec3HBHVCH2gCcpA75g2fsXnUrQnufNqPMd2n9lVQwu6IkG5GZHyRRYSyVJB94Ou+My6FrHLjBGydatBWAqO37jB9cjKKvZzOELvWPXNjrZfR1hJm0XcSohZMXhoyXh9WspTY19z89cvZLPh4ySvcr3ScKQwUuXc90N1st4q2BXhLHCebW2jYp9nGd0jPqL+HJrkpujEdZzcyjoj4WQL5eC7xp2/SbPiuZBPo3Sm5XBrDwjUu2WMUVoq5HisTdU98hSJpaYw7F3pd5UMy6r8p+FCNo61HuVNpBshH51hpiXcRILtz1lhnTRitlIkBhxWB4jFnLSvcnPtg244ZrSTbevMpEhQSFbSi47gESzTy8cJrZ/lpFNQAgLmr8QJcdbwfzOfWmAnXximc8URDpYuE7o2pAwshwW/ItJ5fwXSNz3rH1ZRTmU=
  access_key_id:
    secure: MwFhtHB7KycQWRrRij+g2oV3t5Qq4yXARgszDBcVz0bL7BQa3sOdwINBiOXV0hD8FZ0GNjaa0Q6t+REl0iSh/Q6mlXtbJe1BZ5Y/RI9vPRk1agUIBwxkjW3urkAqR3lMpU3o00ChGSyCfOgPfFp4sAFqpcNVwK7z/uU9Bsg/3dPgt+RQoI5iFORwTS40AOYXXhGuo3scjiKDKNkR29GfSE0PdV14OnzGhrw7CIo8hfqyMqCcFR3p1LNDDnaIZZvZQZtvSUe4hb6uA+jTWmTxYSaQHThqRkB6CAUHDG2BKE7Qr79SoPsz7yCEKc5jp7fuP8JsjAFMfS+JjFj39TOf8+pqvGKW2qxboxHN+vEql8QFKgp+7zYwNcLVAjFFpygBG0aEnT582W3CnCYz47iT08hwvltYG8IjYt/fyaXVvolkkE6HxniSnJcZlhW9rTn/IMAealPq/BgG6oDptwTRlBkBKs9d6butOrISZK50W3G6bprWkZI36SEABfZmpNOOMOfAeHTyZVERbBFeR/rXWDjjwFvFCcGUT6RurgBCQaVCblO7qgbuhEaH6iOkZLiU0xAm2W9qSZAn9k5sZsSeOq21QPIpbuu2b54EUfSTXV2H3L59amb4N06LwOHYmPoNbtEvYRxJifpBj6CFmR1sqcbkAU5vpHuhIB4JHJFtWLE=
